name: "Einreichung Newsletter [de]"
description: "Du kannst diese Vorlage benutzen, um uns eine Einreichung für den Newsletter zukommen zu lassen."
title: "[Artikel]: "
projects: ["newsletter/1"]
assignees:
  -  ClaireWyatt
  -  dstaengle-fzj
body:
  - type: markdown
    attributes:
      value: "Danke, dass Du Dir die Zeit nimmst, etwas für unseren Newsletter zu schreiben!"
  - type: input
    id: title
    attributes:
      label: Titel
      description: "Ein Titel, der den Artikel möglichst kurz beschreibt"
      placeholder: "Bericht über die diesjährige Konferenz „Geschnittenes Brot“"
    validations:
      required: true
  - type: textarea
    id: body
    attributes:
      label: "Artikeltext"
      description: "Bitte benutze dieses Textfeld für den Haupttext des Artikels. Füge Bilder entweder als Anhang oder Link ein."
      placeholder: "Das Konferenzdinner war etwas trocken: es gab Zwieback."
      value: 
    validations:
      required: false
  - type: checkboxes
    id: version
    attributes:
      label: "Bestätigung über die Rechtefreigabe / Lizenz"
      description: "Bitte bestätige hier, dass alles vorgeschlagene Material Dein eigenes Werk sind und dass Du der Veröffentlichung unter der CC0-Lizenz zustimmst."
      options:
        - label: "Ja, ich bestätige"
          required: true
    validations:
      required: true

