name: "Article submission [en]"
description: "You can use this template to propose an article for our newsletter."
title: "[Artikel]: "
projects: ["newsletter/1"]
assignees:
  -  ClaireWyatt
  -  dstaengle-fzj
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to contribute to our newsletter!"
  - type: input
    id: title
    attributes:
      label: Title
      description: "A title describing the article as briefly as possible"
      placeholder: "report on this year‘s conference “Sliced Bread”"
    validations:
      required: true
  - type: textarea
    id: body
    attributes:
      label: "Article text"
      description: "Please use this form field for the main article text"
      placeholder: 
      value: 
    validations:
      required: false
  - type: checkboxes
    id: version
    attributes:
      label: "Confirmation of usage rights / license"
      description: "Please confirm that any submitted and proposed material is your own and that you agree to license is using the CC0 license."
      options:
        - label: "Yes, I confirm"
          required: true
    validations:
      required: true

