name: "Article submission [en]"
description: "You can use this template to propose an article for our newsletter."
title: "Use a great, short title for your article here"
projects: ["newsletter/1"]
assignees:
  -  ClaireWyatt
  -  dstaengle-fzj
body:
  - type: markdown
    attributes:
      value: "Thank you for your contribution to the de-RSE newsletter! To help us share your news with the community, include all relevant details (such as title, article text, dates, links, and contact information, etc.). We look forward to featuring your submission."
  - type: textarea
    id: body
    attributes:
      label: "Article text"
      description: "Please use this form field for the main article text"
      placeholder: 
      value: 
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: "Further link"
      description: "Please provide a link for further reading, if any"
      placeholder: 
      value: 
    validations:
      required: false
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: "Please provide a category of your submission"
      multiple: false
      options:
        - Conferences & Meetups
        - Trainings and Workshops
        - Jobs & Opportunities
        - Funding & Grants
        - Tools and Tips
        - Community News (de-RSE or elsewhere in Germany)
        - Recommended Reading, Listening or Viewing
      default: 0
    validations:
      required: true
  - type: checkboxes
    id: version
    attributes:
      label: "Confirmation of usage rights / licence"
      description: "Please confirm that any submitted and proposed material is your own and that you agree to licence it using the CC0 licence."
      options:
        - label: "Yes, I confirm"
          required: true
    validations:
      required: true

